build:
  nodes:

    analysis:
      environment:
        php:
          version: 7.2
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true

    coverage:
      environment:
        php:
          version: 7.2
          pecl_extensions:
            - redis
        variables:
          REDIS_HOST: localhost
      services:
        redis-timeseries:
          image: redislabs/redistimeseries:1.0.3
          ports:
            - 6379
      tests:
        override:
          - command: vendor/bin/phpunit
            coverage:
              file: build/coverage.xml
              format: 'php-clover'

    psalm:
      environment:
        php:
          version: 7.2
          pecl_extensions:
            - redis
      tests:
        override:
          - command: vendor/bin/psalm

filter:
  excluded_paths:
    - 'tests/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
